Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IEP_Auctions.Models
{
    public class Login
    {
        [Display(Name = "Email")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Fill in email")]
        public string email { get; set; }

        [Display(Name = "Password")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Fill in password")]
        [DataType(DataType.Password)]
        public string password { get; set; }

    }
}

Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Validation;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Reflection;
using System.Net;
using IEP_Auctions.Hubs;
using IEP_Auctions.Models;
using System.Data;
using System.Data.SqlClient;
using System.Windows.Forms;
using System.Threading;
using Microsoft.AspNet.Identity;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.html.simpleparser;
using iTextSharp.tool.xml;
using System.Text.RegularExpressions;

namespace IEP_projekat.Controllers
{
    public class AuctionController : Controller
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private Database db = new Database();

        [HttpGet]
        //[Authorize]
        public ActionResult CreateAuction()
        {
            log.Info("Action Auction/CreateAuction has been fired.");
            if (Session["User"] == null) return RedirectToAction("Login", "User");
            AdminConfiguration ac = db.AdminConfiguration.FirstOrDefault();
            ViewBag.Currency = ac.currency;
            return View();
        }

        [HttpPost]
        //[Authorize]
        public ActionResult CreateAuction(AuctionMetadata am)
        {
            log.Info("Post action Auction/CreateAuction has been fired.");
            string message = "";
            bool status = false;

            if (Session["User"] == null) return RedirectToAction("Login", "User");

            //validate model
            if (am.imageFile != null && ModelState.IsValid)
            { 
                var config = db.AdminConfiguration.FirstOrDefault();

                byte[] image = new byte[am.imageFile.ContentLength];
                am.imageFile.InputStream.Read(image, 0, image.Length);

                Auction auction = new Auction();
                User user = (User)Session["User"];
                auction.userID = user.userID;
                auction.created = DateTime.Now;
                auction.status = "READY";
                if (am.duration == null) auction.duration = config.auctionDuration;
                else auction.duration = (long)am.duration;
                auction.name = am.name;
                auction.startingPrice = (float)am.startingPrice;
                auction.currentPrice = auction.startingPrice;
                auction.currentTokenPrice = (int)Math.Ceiling(am.startingPrice / config.tokenValue);
                auction.currency = config.currency;
                auction.tokenValue = config.tokenValue;
                auction.image = image;

                using (Database db = new Database())
                {
                    db.Auction.Add(auction);
                    try
                    {
                        db.SaveChanges();
                    }
                    catch (DbEntityValidationException ex)
                    {
                        foreach (var entityValidationErrors in ex.EntityValidationErrors)
                        {
                            foreach (var validationError in entityValidationErrors.ValidationErrors)
                            {
                                Response.Write("Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                            }
                        }
                    }
                }
                status = true;
                message = "Creating auction successful";

            }
            else
            {
                message = "Invalid request";
            }

            ViewBag.Message = message;
            ViewBag.Status = status;
            return View(am);
        }

        [HttpGet]
        public ActionResult BidAuction(Guid? auctionID) 
        {
            log.Info("Action Auction/BidAuction has been fired.");
            if (auctionID == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (Session["User"] != null)
            {
                User user = (User)Session["User"];
                if (user.userType.Trim().Equals("user")) ViewBag.LoggedIn = 1;
                else ViewBag.LoggedIn = 2;
            }
            else ViewBag.LoggedIn = 0;

            if (TempData["PDF"] != null) ViewBag.PDF = true;

            AuctionView av = new AuctionView((Guid)auctionID);
            return View(av);
        }

        [HttpPost]
        public ActionResult BidAuction(int? amount, Guid? auctionID)
        {
            log.Info("Post action Auction/BidAuction has been fired.");
            if (Session["User"] == null) return RedirectToAction("Login", "User");

            if (auctionID == null || amount == null)
            {
                return RedirectToAction("Index", "Home");
            }

            string message = "";
            bool success = false;

            SqlConnection MyConnection = new SqlConnection("Server=tcp:serversm150336.database.windows.net,1433;Initial Catalog=IEPsm150336db;Persist Security Info=False;User ID=sm150336;Password=B5b614D7376b;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;");

            SqlDataAdapter MyDataAdapter = new SqlDataAdapter("spCreateBid", MyConnection);

            MyDataAdapter.SelectCommand.CommandType = CommandType.StoredProcedure;

            MyDataAdapter.SelectCommand.Parameters.Add(new SqlParameter("@UserID", SqlDbType.UniqueIdentifier));
            MyDataAdapter.SelectCommand.Parameters["@UserID"].Value = (Guid)Session["UserID"];

            MyDataAdapter.SelectCommand.Parameters.Add(new SqlParameter("@AuctionID", SqlDbType.UniqueIdentifier));
            MyDataAdapter.SelectCommand.Parameters["@AuctionID"].Value = (Guid) auctionID;

            MyDataAdapter.SelectCommand.Parameters.Add(new SqlParameter("@Tokens", SqlDbType.Int));
            MyDataAdapter.SelectCommand.Parameters["@Tokens"].Value = (int) amount;

            MyDataAdapter.SelectCommand.Parameters.Add(new SqlParameter("@StatusCode", SqlDbType.Int));
            MyDataAdapter.SelectCommand.Parameters["@StatusCode"].Direction = ParameterDirection.Output;

            int status = Bid.ExecuteInsertBid(MyDataAdapter);
            MyConnection.Close();

            if (status == 0) Bid.AlertBidInsert((Guid)auctionID, (Guid)Session["UserID"], (int)amount);

            switch (status)
            {
                case 0:
                    message = "Successfull bidding!";
                    success = true;
                    break;
                case 1:
                    message = "You do not have enough tokens!";
                    break;
                case 2:
                    message = "Higher bid exists!";
                    break;
                case 3:
                    message = "The auction is completed!";
                    break;
            }
            
            ViewBag.Message = message;
            ViewBag.Success = success;
            AuctionView av = new AuctionView((Guid)auctionID);
            return View(av);
        }

        //[AjaxOnly]
        public void CompleteAuction(Guid auctionID)
        {
            if (Request.IsAjaxRequest())
            {
                Auction.CompleteAuction(auctionID);
            }
        }

        public ActionResult StartAuction(Guid? auctionID)
        {
            log.Info("Action Auction/StartAuction has been fired.");
            if (Session["User"] == null) return RedirectToAction("Login", "User");
            User user = (User)Session["User"];
            if (!user.userType.Trim().Equals("admin")) return RedirectToAction("Login", "User");
            if (auctionID == null) return RedirectToAction("Index", "Home");

            int status = Auction.StartAuction((Guid)auctionID);
            string adminMessage = "";
            bool adminStatus = false;

            switch (status)
            {
                case 0:
                    adminMessage = "Auction has been started successfully!";
                    adminStatus = true;
                    break;
                case 1:
                    adminMessage = "Auction could not be started! It has either already started or is completed.";
                    break;
            }

            ViewBag.AdminMessage = adminMessage;
            ViewBag.AdminStatus = adminStatus;

            return RedirectToAction("BidAuction", auctionID);

        }

        public ActionResult DeleteAuction(Guid? auctionID)
        {
            log.Info("Action Auction/DeleteAuction has been fired.");
            if (Session["User"] == null) return RedirectToAction("Login", "User");
            User user = (User)Session["User"];
            if (!user.userType.Trim().Equals("admin")) return RedirectToAction("Login", "User");
            if (auctionID == null) return RedirectToAction("Index", "Home");

            int status = Auction.DeleteAuction((Guid)auctionID);
            string adminMessage = "";
            bool adminStatus = false;

            switch (status)
            {
                case 0:
                    adminMessage = "Auction has been deleted successfully!";
                    adminStatus = true;
                    break;
                case 1:
                    adminMessage = "Auction could not be deleted! It has either already started or is completed.";
                    break;
            }

            ViewBag.AdminMessage = adminMessage;
            ViewBag.AdminStatus = adminStatus;

            return View();
        }

        [HttpGet]
        public ActionResult ReviewAuctions()
        {
            log.Info("Action Auction/ReviewAuctions has been fired.");
            if (Session["User"] == null) return RedirectToAction("Login", "User");
            User user = (User)Session["User"];

Controllers/TokenOrderController.cs
using IEP_Auctions.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IEP_Auctions.Controllers
{
    public class TokenOrderController : Controller
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);


        [HttpGet]
        public ActionResult OrderTokens()
        {
            log.Info("Action TokenOrder/OrderTokens has been fired.");
            if (Session["User"] == null) return RedirectToAction("Login", "User");

            using (IEP_Auctions.Models.Database db = new IEP_Auctions.Models.Database())
            {
                AdminConfiguration ac = db.AdminConfiguration.FirstOrDefault();

                ViewBag.Silver = ac.silverPack;
                ViewBag.Gold = ac.goldPack;
                ViewBag.Platinum = ac.platinumPack;

                ViewBag.SilverPrice = ac.silverPack * ac.tokenValue;
                ViewBag.GoldPrice = ac.goldPack * ac.tokenValue;
                ViewBag.PlatinumPrice = ac.platinumPack * ac.tokenValue;

                ViewBag.Currency = ac.currency;

            }

            return View();
        }


        [HttpPost]
        public ActionResult OrderTokens(string pack)
        {
            log.Info("Post action TokenOrder/OrderTokens has been fired.");
            if (Session["User"] == null) return RedirectToAction("Login", "User");

            string message = "";
            bool status = false;

            if (pack == null)
            {
                message = "No token pack selected";
            }
            else
            {
                Guid userID = (Guid)Session["UserID"];
                Guid orderID = IEP_Auctions.Models.TokenOrder.createTokenOrder(userID, pack);

                return Redirect("http://stage.centili.com/payment/widget?apikey=e0b8e3565eaceec89e9077f490848a23&country=rs&reference=" + orderID);
            }

            ViewBag.Message = message;
            ViewBag.Status = status;

            return View();
        }


        public ActionResult SuccessfulPayment(Guid? reference)
        {
            log.Info("Action TokenOrder/SuccessfulPayment has been fired.");
            IEP_Auctions.Models.Database db = new IEP_Auctions.Models.Database();

            using (var trans = db.Database.BeginTransaction(IsolationLevel.Serializable))
            {
                try
                {
                    TokenOrder order = db.TokenOrder.Find(reference);

                    if (order != null && order.state.Trim().Equals("SUBMITTED"))
                    {
                        User user = db.User.Find(order.userID);

                        order.state = "COMPLETED";
                        user.tokens += order.tokens;
                        db.Entry(user).State = EntityState.Modified;
                        db.Entry(order).State = EntityState.Modified;
                        db.SaveChanges();
                        trans.Commit();

                        string mailBody = $"Dear {user.firstName}, your purchase of {order.tokens} tokens succeeded. Thank you for using our services.";
                        MailSender.sendMail(mailBody, "Token Purchase", user.email);

                    }
                }
                catch (Exception ex)
                {
                    trans.Rollback();
                    log.Error("Transaction failed");
                    return RedirectToAction("Index", "Home");
                }
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult FailedPayment(Guid? reference)
        {
            log.Info("Action TokenOrder/FailedPayment has been fired.");

            if (reference == null) return RedirectToAction("Index", "Home");

            IEP_Auctions.Models.Database db = new IEP_Auctions.Models.Database();
            TokenOrder order = db.TokenOrder.Find(reference);
            if (order != null && order.state.Trim().Equals("SUBMITTED"))
            {
                order.state = "CANCELED";
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                User user = db.User.Find(order.userID);
                string mailBody = $"Dear {user.firstName}, your purchase of {order.tokens} tokens failed. Please try again";
                MailSender.sendMail(mailBody, "Token Purchase", user.email);
            }

            return RedirectToAction("Index", "Home");
        }


        public ActionResult TokenOrders(int? itemsPerPage, string searchString, string currentFilter, int? page)
        {
            log.Info("Action TokenOrder/TokenOrders has been fired.");
            if (Session["User"] == null) return RedirectToAction("Login", "User");

            using (IEP_Auctions.Models.Database db = new IEP_Auctions.Models.Database())
            {
                int items;
                if (searchString != null && !searchString.Equals("State"))
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;


                Guid userID = (Guid)Session["UserID"];
                User user = (User)Session["User"];
                ViewBag.Email = user.email;

                List<TokenOrder> tokenOrders = IEP_Auctions.Models.TokenOrder.getTokenOrders(userID);

                if (!String.IsNullOrEmpty(searchString))
                {
                    tokenOrders = tokenOrders.Where(a => a.state.Trim().Equals(searchString)).ToList();
                }

                if (itemsPerPage == null)
                {
                    items = db.AdminConfiguration.FirstOrDefault().itemsPerPage;
                }
                else items = (int)itemsPerPage;

                ViewBag.ItemsPerPage = items;


                int pageNumber = (page ?? 1);
                return View(tokenOrders.ToPagedList(pageNumber, items));
            }
        }

    }
}

Views/User/MyAuctions.cshtml
@model PagedList.IPagedList<IEP_Auctions.Models.Auction>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "My auctions";
}

@using (Html.BeginForm("MyAuctions", "User", FormMethod.Get))
{
    <div class="row m-2">
        <div class="col-sm-12">
            <input class="form-control w-100" style="width: 100%" type="text" placeholder="Search.." name="SearchString" data-toggle="tooltip" data-placement="top" title="Input words separated by spaces" />
        </div>
    </div>
    <div class="row m-2">
        <div class="col-sm-2">
            <input class="form-control" type="number" min="1" placeholder="Min" name="Min" />
        </div>
        <div class="col-sm-2">
            <input class="form-control" type="number" min="1" placeholder="Max" name="Max" />
        </div>
        <div class="col-sm-3">
            <input class="form-control" type="number" min="1" placeholder="Items per page" name="ItemsPerPage" />
        </div>
        <div class="col-sm-3">
            <select class="form-control" name="Status">
                <option selected>State</option>
                <option>READY</option>
                <option>OPENED</option>
                <option>COMPLETED</option>
            </select>
        </div>
        <div class="col-sm-2">
            <input type="submit" value="Filter" class="btn btn-primary text-strong" />
        </div>
    </div>
    <hr />
}

<div class="container-fluid content-row mt-5">
    @{
        int j = 0;
        for (int i = 0; i < Model.Count(); i += 4)
        {
            j = i;

            <div class="row mb-4">

                @while (j < i + 4 && j < Model.Count())
                {
                    <div class="col-sm-3">
                        <div class="card h-100 text-center border-dark">
                            <div class="card-header"><strong>@Model[j].name</strong></div>
                            <a href="@Url.Action("BidAuction", "Auction", new { auctionID = Model[j].auctionID, area = "" })">
                                <img class="card-img-top" src="data:image/png;base64,@Convert.ToBase64String(Model[j].image, 0, Model[j].image.Length)" alt="">
                            </a>
                            <div class="card-body d-flex flex-column">
                                @{
                                    switch (Model[j].status)
                                    {
                                        case "READY":
                                            <span id="status_@Model[j].status" class="badge bg-info">READY</span>
                                            break;
                                        case "OPENED":
                                            <span id="status_@Model[j].status" class="badge bg-success">OPENED</span>
                                            break;
                                        case "COMPLETED":
                                            <span id="status_@Model[j].status" class="badge bg-danger">COMPLETED</span>
                                            break;
                                    }
                                }
                                <p id="time_@Model[j].auctionID" class="card-text mt-auto"></p>
                                <p id="price_@Model[j].auctionID" style="color:green;" class="card-text mt-auto"><b><i>@Model[j].currentPrice @Model[j].currency</i></b></p>
                                <p id="tokens_@Model[j].auctionID" class="card-text mt-auto"><b>@Model[j].currentTokenPrice</b> <img class="img-fluid" src="https://i.postimg.cc/Vkk2nz1y/coins.png" style="width: 20px; height: 20px" /></p>
                                <p id="bidder_@Model[j].auctionID" class="card-text mt-auto text-success">
                                    @if (Model[j].Bid.OrderByDescending(b => b.tokens).FirstOrDefault() != null)
                                    {
                                        <i>@Model[j].Bid.OrderByDescending(b => b.tokens).FirstOrDefault().User.email</i>
                                    }
                                    else
                                    {
                                        <i>Nobody submitted yet</i>
                                    }
                                </p>
                                @{
                                    int min = ((int)Model[j].currentTokenPrice) + 1;


                                    if (Session["User"] != null)
                                    {
                                        switch (Model[j].status)
                                        {
                                            case "READY":
                                                <input type="hidden" id="amount" name="amount" min="@min" value="@min">
                                                <input type="hidden" name="auctionID" value="@Model[j].auctionID" />
                                                <br />
                                                <input type="submit" class="btn btn-primary mt-auto disabled" id="bidBtn_@Model[j].auctionID" value="Bid" />
                                                break;
                                            case "OPENED":
                                                using (Html.BeginForm("BidAuction", "Auction", FormMethod.Post))
                                                {
                                                    <input type="hidden" id="amount" name="amount" min="@min" value="@min">
                                                    <input type="hidden" name="auctionID" value="@Model[j].auctionID" />
                                                    <br />
                                                    <input type="submit" class="btn btn-primary mt-auto" id="bidBtn_@Model[j].auctionID" value="Bid" />
                                                }
                                                break;
                                            case "COMPLETED":
                                                <input type="hidden" id="amount" name="amount" min="@min" value="@min">
                                                <input type="hidden" name="auctionID" value="@Model[j].auctionID" />
                                                <br />
                                                <input type="submit" class="btn btn-primary mt-auto disabled" id="bidBtn_@Model[j].auctionID" value="Bid" />
                                                break;
                                        }
                                    }


                                }
                            </div>
                            </div>
                        </div>

                        if (!Model[j].status.Trim().Equals("COMPLETED") && Model[j].status.Trim().Equals("OPENED"))
                        {
                            <script>

                            var remaining = @Model[j].opened.Value.Ticks/10000000 + @Model[j].duration - @DateTime.Now.Ticks / 10000000;
                            var timer = setInterval(function() {

                                remaining = remaining - 1;

                                //auction over
                                if (remaining <= 0) {
                                    clearInterval(timer);
                                    document.getElementById("status_@Model[j].status").innerHTML = "COMPLETED";
                                    document.getElementById("status_@Model[j].status").className = "badge bg-danger";
                                    document.getElementById("time_@Model[j].auctionID").innerHTML = "";
                                    document.getElementById("bidBtn_@Model[j].auctionID").disabled = true;
                                    $('#bidBtn_@Model[j].auctionID').prop('disabled', true);
                                    $('#bidBtn_@Model[j].auctionID').attr('disabled', 'disabled');

                                $.ajax({
                                    type: "POST",
                                    url: '@Url.Action("CompleteAuction", "Auction", new { auctionID = Model[j].auctionID })',
                                    dataType: "json",
                                    contentType: "application/json; charset=utf-8",
                                    success: function ()
                                    {
                                    }
                                 });

                                return;
                            }

                            //convert seconds to days, hours and minutes
                            var days = Math.floor(remaining / (60 * 60 * 24));
                            var hours = Math.floor((remaining % (60 * 60 * 24)) / (60 * 60));
                            var minutes = Math.floor((remaining % (60 * 60)) / (60));
                            var seconds = Math.floor(remaining % (60));
                            document.getElementById("time_@Model[j].auctionID").innerHTML = days + " days " + hours + ":"
                                + minutes + ":" + seconds;

                        }, 1000);

                            </script>
                        }

                        j++;
                    }
            </div>


        }
    }
</div>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("MyAuctions", "User",
        new { page, currentFilter = ViewBag.CurrentFilter, min = ViewBag.Min, max = ViewBag.Max, itemsPerPage = ViewBag.ItemsPerPage, status = ViewBag.Status }))

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.3.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>


        $(function () {
            // Reference the auto-generated proxy for the hub.
            var bidHub = $.connection.bidHub;
            // Create a function that the hub can call back to display messages.
            bidHub.client.updateBidPrice = function (auctionID, email, price, tokens, currency) {
                document.getElementById("price_" + auctionID).innerHTML = '<b><i>' + price + " " + currency + '</i></b>';
                document.getElementById("bidder_" + auctionID).innerHTML = '<p><i>' + email + '</i></p>';
                document.getElementById("tokens_" + auctionID).innerHTML = '<b>' + tokens + '</b> <img class="img-fluid" src="https://i.postimg.cc/Vkk2nz1y/coins.png" style="width: 20px; height: 20px" />';
                document.getElementById("bidBtn_" + auctionID).min = tokens + 1;
            };

            $.connection.hub.start().done(function () {
            });
        });
    </script>
}

Views/User/ProfilePage.cshtml
@model IEP_Auctions.Models.UserView

@{
    ViewBag.Title = "ProfilePage";
}

<h2>Profile page</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tokens)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tokens)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userType)
        </dd>

    </dl>
    @if (ViewBag.UserType.Equals("admin"))
    {
        <hr />
        <img src="https://i.postimg.cc/KjHh7jJR/settings_2.png" style="width:50px; height:50px" /> @Html.ActionLink("Edit configurations", "EditConfiguration", "User")
        <hr />
        <img src="https://i.postimg.cc/G3Q28jR5/approve.png" style="width:50px; height:50px" /> @Html.ActionLink("Review auctions", "ReviewAuctions", "Auction")
    }
    <hr />
    <img src="https://i.postimg.cc/wMMvySW9/settings_1.png" style="width:50px; height:50px" /> @Html.ActionLink("Edit user details", "EditUser", "User")
    <hr />
    <img src="https://i.postimg.cc/JnCNnQ8h/auction_2.png" style="width:50px; height:50px" /> @Html.ActionLink("Won auctions", "WonAuctions", "User")
    <hr />
    <img src="https://i.postimg.cc/prYqx6nx/auction_1.png" style="width:50px; height:50px" /> @Html.ActionLink("My auctions", "MyAuctions", "User")
    <hr />
    <img src="https://i.postimg.cc/QdJHzkWG/ecommerce.png" style="width:50px; height:50px" /> @Html.ActionLink("List of token orders", "TokenOrders", "TokenOrder")
    <hr />
    <img src="https://i.postimg.cc/x8gt1bXX/hand.png" style="width:50px; height:50px" /> @Html.ActionLink("Order tokens", "OrderTokens", "TokenOrder")

</div>